# version: '3.9'

# services:
#   backend:
#     build:
#       context: .
#       dockerfile: backend/Dockerfile
#     container_name: kama_backend
#     ports:
#       - "5000:5000"
#     volumes:
#       - D:/images:/app/uploads
#     env_file:
#       - backend/.env

#   frontend:
#     build:
#       context: .
#       dockerfile: frontend/Dockerfile
#     container_name: kama_frontend
#     ports:
#       - "5173:5173"

   



version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: kama_backend
    ports:
      - "5000:5000"
    volumes:
      - D:/images:/app/uploads
    env_file:
      - backend/.env
    networks:
      - kama_net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: kama_frontend
    ports:
      - "5173:5173"
    networks:
      - kama_net

networks:
  kama_net:
    driver: bridge
